#!/bin/bash -l
# =============================================================================
# pbs_qwen25_translate.sh — Fortran -> JAX initial translation authored by
#                           Qwen2.5-Coder-32B-Instruct via vLLM: the LAFT
#                           paper-1 configuration.
#
# This is the setup that produced kessler/translations/qwen25-32b-jd/ in
# April 2026, expressed through the framework's Qwen driver
# (workflow_translator/qwen/qwen_API_translate.py) instead of the original
# per-procedure script:
#   model            Qwen2.5-Coder-32B-Instruct, bfloat16, local weights
#   context window   max_model_len 24576
#   output cap       16384 tokens per pass (fixed, not adaptive)
#   sampling         temperature 0.1, top-p / top-k / min-p / repetition
#                    penalty at vLLM defaults, unseeded
#   reasoning        off (Qwen2.5 has no thinking mode; the flag is a no-op)
#   RoPE scaling     none
#   tensor parallel  2 GPUs (A100-40GB; ~65 GB of BF16 weights sharded 2-way)
#   prompts          the same four-pass prompts every model received
#                    (out/prompts/{proc}_pass{n}.md, regenerated by phase04_01)
# Sampling at temperature 0.1 is not deterministic across runs, so a rerun
# reproduces the configuration, not the archived bytes. The archived files
# are what the paper validated.
#
# Submit (all procedures, from the project root):
#   qsub pbsJobs/pbs_qwen25_translate.sh
# Re-roll specific procedures:
#   qsub -v PROCS=kessler_run pbsJobs/pbs_qwen25_translate.sh
# Resume after a partial run:
#   qsub -v PROCS=all,SKIP_EXISTING=1 pbsJobs/pbs_qwen25_translate.sh
# Overrides (qsub -v):
#   MODEL=/path/to/Qwen2.5-Coder-32B-Instruct   weights directory
#   QWEN_ENV=<conda env>                        default qwen-vllm (envs/qwen-vllm.yml:
#                                               vLLM 0.15.1 / Python 3.11, the
#                                               April 2026 environment)
#   SEED=<int>                                  pin the sampling seed (default: unseeded)
#
# Log:      out/jobs/qwen25_translate.o<JOBID>
# Output:   out/jax/{proc}_pass{n}.py (intermediates), out/jax/{proc}.py (finals)
# Before submitting, set [translator] in config/project.toml to this job
# (source = "qwen", llm_label = "Qwen2.5-32B (Qwen2.5-Coder-32B-Instruct via vLLM)",
# pbs_translate_job = "pbsJobs/pbs_qwen25_translate.sh") — the driver stamps
# llm_label into every output file's version header.
# =============================================================================

#PBS -A <PROJECT_CODE>
#PBS -q develop
#PBS -j oe
#PBS -o out/jobs/
#PBS -N qwen25_translate
#PBS -l select=1:ncpus=8:ngpus=2:mem=64GB
#PBS -l walltime=02:00:00

set -euo pipefail

echo "============================================"
echo " Qwen2.5-Coder-32B Fortran -> JAX translation (paper-1 configuration)"
echo " Host    : $(hostname)"
echo " Started : $(date)"
echo " PROCS   : ${PROCS:-all}"
echo "============================================"

# --- Load environment -------------------------------------------------------
module purge
module load conda/latest
QWEN_ENV="${QWEN_ENV:-qwen-vllm}"
conda activate "${QWEN_ENV}"

# Newer vLLM envs ship their own CUDA 13 toolkit for JIT kernels; use it when
# present (the vLLM 0.15.1 env from envs/qwen-vllm.yml has none and needs nothing here).
SP="$(python -c 'import site; print(site.getsitepackages()[0])')"
if [[ -d "${SP}/nvidia/cu13/bin" ]]; then
    NVLIBS="$(ls -d "${SP}"/nvidia/*/lib 2>/dev/null | tr '\n' ':')"
    export LD_LIBRARY_PATH="${NVLIBS}${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH:-}"
    export CUDA_HOME="${SP}/nvidia/cu13"
    export PATH="${CUDA_HOME}/bin:${PATH}"
    echo "[cuda] CUDA_HOME=${CUDA_HOME} ($(nvcc --version | tail -1))"
fi
export VLLM_USE_FLASHINFER_SAMPLER=0

echo "[gpu] $(nvidia-smi --query-gpu=name,memory.total --format=csv,noheader || true)"

# --- Run --------------------------------------------------------------------
cd "${PBS_O_WORKDIR:?submit this job with qsub from the project root}"
[ -f config/project.toml ] || { echo "ERROR: $PWD is not a LAFT project root (config/project.toml missing)"; exit 1; }

MODEL="${MODEL:-/glade/work/${USER}/models/Qwen2.5-Coder-32B-Instruct}"
if [[ ! -d "${MODEL}" ]]; then
    echo "ERROR: Model directory does not exist: ${MODEL}"
    echo "  Place the weights there (e.g. huggingface-cli download Qwen/Qwen2.5-Coder-32B-Instruct --local-dir ${MODEL}),"
    echo "  or pass MODEL=... via qsub -v."
    exit 1
fi

EXTRA_ARGS=()
if [[ "${SKIP_EXISTING:-0}" == "1" ]]; then
    EXTRA_ARGS+=(--skip-existing)
fi
if [[ -n "${SEED:-}" ]]; then
    EXTRA_ARGS+=(--seed "${SEED}")
fi

# Paper-1 settings are fixed here on purpose; to run another model or
# configuration, copy this job and edit it (see qwen.md §Other Qwen models).
python workflow_translator/qwen/qwen_API_translate.py \
    --model "${MODEL}" \
    --procs "${PROCS:-all}" \
    --tensor-parallel-size 2 \
    --max-model-len 24576 \
    --max-tokens 16384 \
    --temperature 0.1 \
    "${EXTRA_ARGS[@]}"

echo ""
echo "============================================"
echo " Job finished : $(date)"
echo "============================================"
