#!/usr/bin/env python3
# ---------------------------------------------------------------------------
# Generated by: Claude Fable 5 (claude-fable-5)
# Phase 5.1b: Semantic audit — mechanical translation-vs-Fortran comparison
# ---------------------------------------------------------------------------
"""
Deterministic checks that compare each translated procedure (out/jax/<proc>.py)
against its Fortran source (out/procedures/<proc>.F90). These catch the
"paraphrased translation" bug classes found during earlier driver repairs
WITHOUT running any code:

  FAIL-level (gate):
    lut-indices    : the set of proc_from_LUT_*(ind, ...) column indices used
                     per LUT function must match the Fortran's set
                     (caught: M2 — f1pr number used as table column)
    calls-invoked  : every procedure the Fortran calls (call statements ∪ the
                     frontend's calls list) is invoked in the translation body
                     as X( / X_core( / X_value( (caught 2026-08-25:
                     impose_max_Ni imported, never called)

  WARN-level (report, no gate — waivable):
    labelled-blocks: every Fortran labelled construct (name: if/do/select…)
                     is mentioned somewhere in the translation (caught
                     2026-08-25: k_loop_fz homogeneous freezing, calc_HM)
    zero-forever   : a variable the Fortran computes with a real expression is
                     only ever assigned a zero constant in the translation
                     (caught: M1 — qcnuc/ncnuc never computed)
    intent-out     : Fortran intent(out) arguments should be re-initialized at
                     translation entry (caught: M8 — prt_* accumulation)
    missing-consts : numeric literals present in the Fortran body but absent
                     from the translation (caught: KK2000/Cooper constants)

  INFO-level:
    invented-consts: literals in the translation absent from the Fortran
    conventions    : level/index convention claims found in docstrings
                     (e.g. "kbot=1 ... kdir=1") for manual cross-check
                     against the caller (caught: M7 — sedimentation no-op)

Waivers: out/issues/semantic_audit_waivers.json
    { "<proc>": { "<check>": ["name-or-value", ...] } }

Outputs: out/issues/semantic_audit/<proc>.json + _summary.json
Exit code 2 iff any FAIL-level finding remains after waivers.

GATE: _summary.json is what workflow_translator/audit_gate.py inspects before
runtime validation (Step 4) may be recorded or submitted — it must be newer
than every out/jax/<proc>.py and have total_fail == 0. Re-run this script
after every translation fix.
"""
from __future__ import annotations

import json
import re
import sys
from datetime import datetime
from pathlib import Path

# framework_config lives in LAFT/config/; this script now lives in a
# workflow folder symlinked from LAFT/ into each project — resolve back to
# LAFT/config to import it. Same convention as workflow_bridge/phase03_make_bridge.py.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "config"))

from framework_config import get_config

_CFG = get_config()
PROJECT_ROOT = _CFG.root
JAX_DIR   = PROJECT_ROOT / _CFG.jax_dir
F90_DIR   = PROJECT_ROOT / _CFG.procedures_dir
OUT_DIR   = PROJECT_ROOT / _CFG.issues_dir / "semantic_audit"
WAIVERS   = PROJECT_ROOT / _CFG.issues_dir / "semantic_audit_waivers.json"

# Project-specific gates ([semantic_audit] in config/project.toml).
# "lut_indices" and "level_conventions" only make sense for schemes with
# multi-column lookup tables / level-direction conventions;
# projects without them list neither and those checks are skipped.
_SA = _CFG.section("semantic_audit")
ENABLED_CHECKS = set(_SA.get("enabled_checks", []))
LUT_PATTERN = _SA.get("lut_pattern", "proc_from_LUT_")
LEVEL_CONVENTION_NAMES = list(_SA.get("level_convention_names", []))

# literals too generic to be diagnostic
TRIVIAL_CONSTS = {0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0,
                  0.5, 100.0, 1000.0, 0.1, 0.01, 273.15, 1.e-20}


# ---------------------------------------------------------------------------
# source loading / cleaning
# ---------------------------------------------------------------------------
def strip_fortran(src: str) -> str:
    """Drop comments; join continuation lines."""
    lines = []
    for ln in src.splitlines():
        code = re.split(r"!", ln, 1)[0]
        lines.append(code)
    text = "\n".join(lines)
    text = re.sub(r"&\s*\n\s*&?", " ", text)   # continuations
    return text


def _split_top_level(s: str) -> list[str]:
    """Split on commas at paren-depth 0 (array dim specs like `(:,:)` stay intact)."""
    parts, depth, start = [], 0, 0
    for i, ch in enumerate(s):
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        elif ch == "," and depth == 0:
            parts.append(s[start:i])
            start = i + 1
    parts.append(s[start:])
    return parts


def strip_python(src: str) -> str:
    """Drop # comments and docstrings (coarse but adequate)."""
    src = re.sub(r'"""(?:.|\n)*?"""', "", src)
    src = re.sub(r"'''(?:.|\n)*?'''", "", src)
    return "\n".join(re.split(r"#", ln, 1)[0] for ln in src.splitlines())


def find_f90(proc: str) -> Path | None:
    exact = F90_DIR / f"{proc}.F90"
    if exact.exists():
        return exact
    low = proc.lower()
    for p in F90_DIR.glob("*.F90"):
        if p.stem.lower() == low:
            return p
    return None


# ---------------------------------------------------------------------------
# checks
# ---------------------------------------------------------------------------
def check_lut_indices(f_txt: str, p_txt: str) -> list[dict]:
    """Columns the translation uses but Fortran doesn't = FAIL (invented
    mapping). Columns Fortran uses but the translation doesn't = WARN
    (possibly an unported optional path — e.g. liqFrac/3-mom branches)."""
    out = []
    lut = re.escape(LUT_PATTERN)
    f_use: dict[str, set] = {}
    for m in re.finditer(lut + r"(\w+)\s*\(\s*(\d+)", f_txt, re.I):
        f_use.setdefault(m.group(1).lower(), set()).add(int(m.group(2)))
    p_use: dict[str, set] = {}
    for m in re.finditer(lut + r"(\w+?)(?:_core|_value)?\s*\(\s*(\d+)", p_txt, re.I):
        p_use.setdefault(m.group(1).lower(), set()).add(int(m.group(2)))
    # inlined lookups (sedimentation style): attribute to the table in use
    inline = {int(m.group(1)) for m in re.finditer(r"_lut_lookup\(\s*(\d+)", p_txt)}
    if inline:
        key = "main3mom" if "itab_3mom" in p_txt else "main2mom"
        p_use.setdefault(key, set()).update(inline)
    for fn in sorted(set(f_use) | set(p_use)):
        fs, ps = f_use.get(fn, set()), p_use.get(fn, set())
        invented = ps - fs
        unported = fs - ps
        if invented:
            out.append({
                "check": "lut-indices", "severity": "FAIL", "name": fn,
                "detail": f"translation uses columns {sorted(invented)} that "
                          f"the Fortran never uses (fortran set: {sorted(fs)})",
            })
        if unported:
            out.append({
                "check": "lut-indices-unported", "severity": "WARN", "name": fn,
                "detail": f"Fortran uses columns {sorted(unported)} the "
                          "translation never fetches (possibly an unported "
                          "optional path)",
            })
    return out


def check_zero_forever(f_txt: str, p_txt: str) -> list[dict]:
    """WARN: Fortran computes var with an expression; Python only zeroes it."""
    out = []
    # Fortran: names assigned a non-trivial RHS (not just 0)
    f_computed = set()
    for m in re.finditer(r"(?m)^\s*(\w+)\s*(?:\([^)]*\))?\s*=\s*(.+)$", f_txt):
        name, rhs = m.group(1).lower(), m.group(2).strip()
        if not re.fullmatch(r"0\.?0?(?:e0)?d?0?", rhs, re.I):
            f_computed.add(name)
    # Python: assignment map name -> any non-zero RHS seen?
    zeroish = re.compile(r"^(?:0\.?0?|np\.zeros.*|jnp\.zeros.*|"
                         r"np\.zeros_like.*|jnp\.zeros_like.*)$")
    p_assigned: dict[str, bool] = {}
    # A chained assignment `a = b = c = 0.0` is ONE statement assigning the
    # final RHS to every name; without splitting it, `a` was seen with RHS
    # "b = c = 0.0" (non-trivial) and `b`, `c` were never seen at all — this
    # hid never-computed freezing rates in an earlier project.
    chain = re.compile(r"^\s*(\w+)\s*=\s*(.+)$")
    for m in re.finditer(r"(?m)^\s*(\w+)\s*(?:\[[^\]]*\])?\s*[*+-]?=\s*(.+)$", p_txt):
        names = [m.group(1).lower()]
        rhs = m.group(2).strip().rstrip(";")
        # peel `name =` prefixes (plain `=` only; `==`, `<=`, `>=`, `!=` are not chains)
        while True:
            c = chain.match(rhs)
            if not c or rhs[len(c.group(1)):].lstrip().startswith("=="):
                break
            names.append(c.group(1).lower())
            rhs = c.group(2).strip()
        nontrivial = not zeroish.fullmatch(rhs)
        for name in names:
            p_assigned[name] = p_assigned.get(name, False) or nontrivial
    for name, has_real in sorted(p_assigned.items()):
        if not has_real and name in f_computed:
            out.append({
                "check": "zero-forever", "severity": "WARN", "name": name,
                "detail": "translation only ever assigns a zero constant, "
                          "but the Fortran computes this variable",
            })
    return out


def check_intent_out(f_txt: str, p_txt: str) -> list[dict]:
    """WARN: intent(out) args should be re-initialized in the translation."""
    out = []
    names = set()
    for m in re.finditer(r"(?im)^\s*[^!\n]*intent\s*\(\s*out\s*\)[^:]*::(.+)$", f_txt):
        for nm in _split_top_level(m.group(1)):
            nm = nm.strip().split("(")[0].strip().lower()
            if nm:
                names.add(nm)
    for nm in sorted(names):
        # violated only when every assignment to the name carries the incoming
        # value forward (RHS references the name itself, e.g. np.array(nm)) —
        # a fresh computation or a zero/full reset both count as satisfied
        assigns = re.findall(
            rf"(?m)^\s*{re.escape(nm)}\s*(?:\[[^\]]*\])?\s*=\s*(.+)$", p_txt)
        if not assigns:
            fresh = False
        else:
            fresh = any(not re.search(rf"\b{re.escape(nm)}\b", rhs)
                        for rhs in assigns)
        if not fresh:
            out.append({
                "check": "intent-out", "severity": "WARN", "name": nm,
                "detail": "Fortran intent(out) arg is only ever copied from "
                          "its incoming value (or never assigned) — risk of "
                          "accumulation across calls",
            })
    return out


_FLOAT_RE = re.compile(r"(?<![\w.])(\d+\.\d*(?:[eEdD][+-]?\d+)?|"
                       r"\d+(?:[eEdD][+-]?\d+)|\.\d+(?:[eEdD][+-]?\d+)?)")


def _consts(text: str) -> set[float]:
    vals = set()
    for m in _FLOAT_RE.finditer(text):
        try:
            v = float(m.group(1).lower().replace("d", "e"))
        except ValueError:
            continue
        if v not in TRIVIAL_CONSTS and v == v:  # skip trivials and NaN
            vals.add(round(v, 6) if v < 1e6 else v)
    return vals


def check_constants(f_txt: str, p_txt: str) -> list[dict]:
    out = []
    f_c, p_c = _consts(f_txt), _consts(p_txt)
    missing = sorted(f_c - p_c)
    invented = sorted(p_c - f_c)
    if missing:
        out.append({
            "check": "missing-consts", "severity": "WARN", "name": "constants",
            "detail": f"{len(missing)} Fortran literal(s) absent from "
                      f"translation: {missing[:15]}"
                      + (" ..." if len(missing) > 15 else ""),
            "values": missing,
        })
    if invented:
        out.append({
            "check": "invented-consts", "severity": "INFO", "name": "constants",
            "detail": f"{len(invented)} literal(s) in translation absent from "
                      f"Fortran: {invented[:15]}"
                      + (" ..." if len(invented) > 15 else ""),
            "values": invented,
        })
    return out


def _deps_calls() -> dict[str, list[str]]:
    """proc -> callee list from the frontend's _ALL_deps.json (case as written)."""
    try:
        deps = json.loads(Path(_CFG.all_deps_file).read_text(encoding="utf-8"))
    except (OSError, ValueError, AttributeError):
        return {}
    return {e["proc_name"].lower(): list(e.get("calls", []) or []) for e in deps}


_DEPS_CALLS = _deps_calls()


def check_calls_invoked(proc: str, f_txt: str, p_txt: str) -> list[dict]:
    """FAIL (4a, 2026-08-25): every procedure the Fortran calls must be
    invoked in the translation BODY. Sources: `call X(` statements in the
    comment-stripped Fortran ∪ the frontend's per-procedure `calls` list
    (function references are not `call` statements). A live invocation may be
    spelled X(, X_core(, X_value( or a private _X_core( / _X_value( — the
    bridge-contract core splits. Import lines never match (no paren after the
    name). Waivable per proc for deliberately unported optional paths
    (caught 08-25: impose_max_Ni imported but never called → Ni 8× high)."""
    out = []
    callees = {m.group(1).lower() for m in
               re.finditer(r"^\s*call\s+(\w+)", f_txt, re.I | re.M)}
    callees |= {c.lower() for c in _DEPS_CALLS.get(proc.lower(), [])}
    callees.discard(proc.lower())
    # only PROJECT procedures count: Fortran intrinsics (cpu_time), host-model
    # services (physeterror, rpn_comm_*) and library calls are not translation
    # targets — they are frontend-index members or have a packet F90 file.
    project = set(_DEPS_CALLS) | {p.stem.lower() for p in F90_DIR.glob("*.F90")}
    callees = {c for c in callees if c in project}
    for c in sorted(callees):
        pat = re.compile(rf"(?<![\w])_?{re.escape(c)}(?:_core|_value)?\s*\(", re.I)
        if not pat.search(p_txt):
            out.append({
                "check": "calls-invoked", "severity": "FAIL", "name": c,
                "detail": f"Fortran calls `{c}` but the translation body never "
                          f"invokes {c}( / {c}_core( / {c}_value( — dropped, or an "
                          "optional path not ported (waive with justification)",
            })
    return out


def check_labelled_blocks(f_txt: str, p_src_raw: str) -> list[dict]:
    """WARN (4b, 2026-08-25): every Fortran labelled construct
    (`name: if / do / select / where / block`) must appear — as an identifier,
    comment or docstring text — in the translation. Cheap "block never ported"
    detector (caught 08-25: k_loop_fz homogeneous freezing, calc_HM)."""
    out = []
    labels = []
    for m in re.finditer(r"^\s*(\w+)\s*:\s*(?:if|do|select|where|block|forall)\b",
                         f_txt, re.I | re.M):
        lab = m.group(1)
        if lab.lower() not in {l.lower() for l in labels}:
            labels.append(lab)
    low = p_src_raw.lower()
    for lab in labels:
        if lab.lower() not in low:
            out.append({
                "check": "labelled-blocks", "severity": "WARN", "name": lab,
                "detail": f"Fortran labelled block `{lab}:` is not mentioned anywhere "
                          "in the translation (identifier, comment or docstring) — "
                          "block possibly not ported; name it where it lives, or waive",
            })
    return out


# --- 3: prognostic update-block completeness --------------------------------
# [semantic_audit].prognostic_vars = ["qc", "nc", "qitot:qit", ...]
# Each entry is "<fortran name>" or "<fortran name>:<translation name>" when the
# translation uses a local alias (e.g. a per-category qitot(i,k,iice) → qit).
PROGNOSTIC_VARS = [str(v) for v in _SA.get("prognostic_vars", [])]

_TERM_STOP = {"dt", "i", "k", "j", "iice", "icat", "n", "sum", "max", "min", "merge",
              "real", "dble", "sngl", "abs", "exp", "log", "sqrt", "where", "jnp", "np",
              "lax", "true", "false", "none", "and", "or", "not", "if", "else"}


def _terms(expr: str) -> set[str]:
    """Identifiers in an update expression (lower-case), minus indices,
    intrinsics and numpy namespaces; `jnp.where(m, x, y)` contributes x/y's
    identifiers like any other sub-expression."""
    ids = {m.group(0).lower() for m in re.finditer(r"(?<![\w.])[A-Za-z_]\w*", expr)}
    return {t for t in ids if t not in _TERM_STOP and not t.startswith("_")}


def _fortran_update_terms(f_txt: str, var: str) -> set[str]:
    """Union of term identifiers over every `var(...) = var(...) ± (...)`
    statement in the Fortran (continuations already joined)."""
    terms = set()
    # index lists `(i,k)` / `(i,k,iice)` never nest parens — keep the optional
    # group flat, or it greedily swallows the whole `(-a-b-c)` expression and
    # leaves only the last term (bug found on first run, 2026-08-25)
    idx = r"(?:\([^()=\n]*\))?"
    pat = re.compile(rf"^\s*{re.escape(var)}\s*{idx}\s*=\s*{re.escape(var)}\s*{idx}\s*([-+].*)$",
                     re.I | re.M)
    for m in pat.finditer(f_txt):
        terms |= _terms(m.group(1))
    return terms - {var.lower()}


def _join_python_continuations(p_txt: str) -> str:
    """Join lines while parentheses/brackets are open, so a multi-line
    `x = x + ((a) +\n (b)) * dt` is one statement for the regexes."""
    out, buf, depth = [], [], 0
    for ln in p_txt.splitlines():
        buf.append(ln if not buf else ln.strip())
        depth += ln.count("(") + ln.count("[") - ln.count(")") - ln.count("]")
        if depth <= 0:
            out.append(" ".join(buf)); buf, depth = [], 0
    if buf:
        out.append(" ".join(buf))
    return "\n".join(out)


def _assignments(txt: str, name: str, fortran: bool) -> set[str]:
    """Terms of every plain assignment `name = expr` (Fortran: `name(...) = expr`
    too) — used to expand a temporary one level (tmp1 = (a+b)*dt → {a, b})."""
    idx = r"(?:\([^()=\n]*\))?" if fortran else ""
    terms = set()
    for m in re.finditer(rf"^\s*{re.escape(name)}\s*{idx}\s*=\s*(?!=)([^\n]*)$", txt,
                         re.I | re.M):
        rhs = m.group(1)
        # a self-update `x = x + ...` is not a definition of a temporary
        if re.match(rf"\s*{re.escape(name)}\b", rhs, re.I):
            continue
        terms |= _terms(rhs)
    return terms - {name.lower()}


def _expand(missing: set[str], have: set[str], src_txt: str, fortran: bool,
            depth: int = 2) -> tuple[set[str], set[str]]:
    """Resolve names in `missing` through their own definitions on the source
    side: a term is satisfied if it is in `have` or if every term of its
    definition is (recursively, `depth` levels). Returns (still_missing,
    resolved_via)."""
    still, resolved = set(), set()
    for t in missing:
        if t in have:
            continue
        defs = _assignments(src_txt, t, fortran)
        if defs and depth > 0:
            sub, _ = _expand(defs, have, src_txt, fortran, depth - 1)
            if not sub:
                resolved.add(t)
                continue
        still.add(t)
    return still, resolved


def _expandable(txt: str, fortran: bool) -> set[str]:
    """All identifiers that are assigned somewhere on this side (so a name
    defined only as a temporary here counts as 'present' when the other side
    references the same physics through the expanded expression)."""
    idx = r"(?:\([^()=\n]*\))?" if fortran else ""
    return {m.group(1).lower() for m in
            re.finditer(rf"^\s*([A-Za-z_]\w*)\s*{idx}\s*=(?!=)", txt, re.M)}


def _python_update_terms(p_txt: str, var: str) -> set[str]:
    """Union over `var = var ± ...`, `var += ...`, `var -= ...` and
    `var = jnp.where(..., var ± ..., var)` statements in the translation."""
    terms = set()
    p_txt = _join_python_continuations(p_txt)
    v = re.escape(var)
    for m in re.finditer(rf"^\s*{v}\s*=\s*{v}\s*([-+][^\n]*)$", p_txt, re.M):
        terms |= _terms(m.group(1))
    for m in re.finditer(rf"^\s*{v}\s*[-+]=\s*([^\n]*)$", p_txt, re.M):
        terms |= _terms(m.group(1))
    for m in re.finditer(rf"^\s*{v}\s*=\s*(?:jnp|np)\.where\((.*?{v}\s*[-+].*)\)\s*$", p_txt, re.M):
        terms |= _terms(m.group(1))
    return terms - {var.lower()}


def check_update_terms(f_txt: str, p_txt: str) -> list[dict]:
    """3 (2026-08-25): for each configured prognostic variable, the set of
    identifiers in the Fortran's `x = x ± (...)` update statements must all
    appear in the translation's updates of the same variable — FAIL (missing
    term = a computed rate never applied; caught 08-25: qcheti/qrheti/*mul
    absent from 8 update lines). Extra translation terms are WARN. Only
    procedures that update the variable are checked; n/a without config."""
    out = []
    alias = {}
    for entry in PROGNOSTIC_VARS:          # fortran name -> translation name
        f_name, _, p_name = entry.partition(":")
        alias[f_name.lower()] = (p_name or f_name).lower()
    for entry in PROGNOSTIC_VARS:
        f_name, _, p_name = entry.partition(":")
        p_name = p_name or f_name
        f_terms = _fortran_update_terms(f_txt, f_name)
        if not f_terms:
            continue                       # this procedure does not update it
        # a prognostic variable used as a TERM (cleanup: qv = qv + qitot) is
        # spelled with its translation alias on the Python side
        f_terms = {alias.get(t, t) for t in f_terms}
        # the alias is the caller-local name (the orchestrator's cell); other procedures
        # keep the Fortran name — accept updates under either spelling
        p_terms = _python_update_terms(p_txt, p_name)
        if p_name.lower() != f_name.lower():
            p_terms |= _python_update_terms(p_txt, f_name)
        if not p_terms:
            out.append({
                "check": "update-terms", "severity": "FAIL", "name": f_name,
                "detail": f"Fortran updates `{f_name}` with terms {sorted(f_terms)} but no "
                          f"`{p_name} = {p_name} ± …` / `{p_name} += …` update was found in "
                          "the translation (renamed? add an alias `fortran:python` in "
                          "[semantic_audit].prognostic_vars)",
            })
            continue
        # temporaries: a Fortran `tmp1 = (a+b)*dt; x = x + tmp1` versus a
        # translation `x = x + (a + b) * dt` (or vice versa) must not fail on the
        # temporary's NAME — expand each unmatched name through its definition
        # on its own side, up to two levels, before declaring it missing/extra.
        p_all = p_terms | {alias.get(t, t) for t in _expandable(p_txt, False)}
        missing, _ = _expand(f_terms - p_terms, p_terms | p_all, f_txt, True)
        f_all = f_terms | _expandable(f_txt, True)
        extra, _ = _expand(p_terms - f_terms, f_terms | {alias.get(t, t) for t in f_all},
                           _join_python_continuations(p_txt), False)
        missing, extra = sorted(missing), sorted(extra)
        for t in missing:
            out.append({
                "check": "update-terms", "severity": "FAIL", "name": f"{f_name}:{t}",
                "detail": f"term `{t}` is in the Fortran update of `{f_name}` but absent from "
                          f"the translation's update of `{p_name}` (rate computed but never "
                          "applied, or an unported optional path — waive with justification)",
            })
        if extra:
            out.append({
                "check": "update-terms-extra", "severity": "WARN", "name": f_name,
                "detail": f"translation's update of `{p_name}` has terms {extra} that the "
                          f"Fortran update of `{f_name}` does not (helper/guard names, or an "
                          "invented term — check)",
            })
    return out


# --- 2: lookup-table read index base ---------------------------------------
# [semantic_audit].table_readers = [
#   { proc = "xyz_init", function = "_read_table1", result_index = 0,
#     file = "data/lookup_tables/table1.dat",
#     fortran_read = "itab(jj,ii,ll,i,", header_lines = 2 }, ... ]
# The Fortran `read(...) dum,…, <prefix>1), <prefix>2), … <prefix>N)` statement
# gives the token skip and column count; the reader is executed on the real
# file (numpy only — the function's source is extracted with `ast` and run
# WITHOUT importing the translation module, so no jax on the login node) and
# the first two records are compared with the raw file tokens.
TABLE_READERS = list(_SA.get("table_readers", []))


def _fortran_read_layout(f_txt: str, prefix: str) -> tuple[int, int, list[str], str] | None:
    """(skip_tokens, ncols, index_names, innermost_loop_var) from the Fortran
    read statement whose item list contains `prefix`; None if not found."""
    pfx = re.escape(prefix)
    m = re.search(rf"^\s*read\s*\([^)]*\)\s*(.*{pfx}.*)$", f_txt, re.I | re.M)
    if not m:
        return None
    items = [it.strip() for it in _split_top_level(m.group(1))]
    skip = next((i for i, it in enumerate(items) if it.lower().startswith(prefix.lower())),
                None)
    if skip is None:
        return None
    cols = [int(c) for c in re.findall(rf"{pfx}\s*(\d+)\s*\)", m.group(1), re.I)]
    names = [n.strip() for n in prefix[prefix.index("(") + 1:].rstrip(",").split(",")]
    loops = re.findall(r"^\s*do\s+(\w+)\s*=", f_txt[:m.start()], re.I | re.M)
    innermost = loops[-1].lower() if loops else ""
    return skip, max(cols), names, innermost


def _exec_reader(module_path: Path, func: str):
    """Return the reader function executed in a numpy-only namespace built
    from the translation's top-level constants and function definitions
    (imports of jax are skipped on purpose)."""
    import ast
    import numpy as np
    tree = ast.parse(module_path.read_text(encoding="utf-8"))
    keep = [n for n in tree.body
            if isinstance(n, ast.FunctionDef)
            or (isinstance(n, ast.Assign) and not any(
                isinstance(v, (ast.Call, ast.Attribute)) for v in ast.walk(n.value)))]
    ns = {"np": np, "__name__": "audit_reader"}
    exec(compile(ast.Module(body=keep, type_ignores=[]), str(module_path), "exec"), ns)
    if func not in ns:
        raise KeyError(func)
    return ns[func]


def check_table_reads(proc: str, f_txt: str) -> list[dict]:
    """2 (2026-08-25): the translation's table reader must place Fortran
    column `ind` at 0-based slot `ind-1`, read the same number of columns
    after the same number of leading dummies, and honour the Fortran loop
    nesting order. FAIL (caught 08-25: a table reader stored table-1 columns at
    slots 1..19 → every lookup read the neighbouring column)."""
    import numpy as np
    out = []
    for cfg in TABLE_READERS:
        if str(cfg.get("proc", "")).lower() != proc.lower():
            continue
        prefix = str(cfg["fortran_read"])
        layout = _fortran_read_layout(f_txt, prefix)
        name = f"{cfg.get('function')}[{prefix}]"
        if layout is None:
            out.append({"check": "table-reads", "severity": "WARN", "name": name,
                        "detail": f"no Fortran read statement containing `{prefix}` found — "
                                  "check [semantic_audit].table_readers.fortran_read"})
            continue
        skip, ncols, idx_names, innermost = layout
        path = PROJECT_ROOT / str(cfg["file"])
        if not path.exists():
            out.append({"check": "table-reads", "severity": "WARN", "name": name,
                        "detail": f"table file {path} not found — cannot execute the reader"})
            continue
        try:
            reader = _exec_reader(JAX_DIR / f"{proc}.py", str(cfg["function"]))
            res = reader(str(path))
            table = np.asarray(res[int(cfg.get("result_index", 0))]
                               if isinstance(res, (tuple, list)) else res, dtype=float)
        except Exception as exc:  # noqa: BLE001 — report, don't crash the audit
            out.append({"check": "table-reads", "severity": "WARN", "name": name,
                        "detail": f"could not execute reader: {type(exc).__name__}: {exc}"})
            continue
        # raw records: first two data lines after the header
        lines = [ln for ln in path.read_text(encoding="utf-8", errors="replace").splitlines()
                 if ln.strip()]
        recs = []
        for ln in lines[int(cfg.get("header_lines", 1)):]:
            try:
                recs.append([float(t.replace("D", "e").replace("d", "e")) for t in ln.split()])
            except ValueError:
                continue
            if len(recs) == 2:
                break
        if len(recs) < 2 or len(recs[0]) < skip + ncols:
            out.append({"check": "table-reads", "severity": "WARN", "name": name,
                        "detail": "could not parse two data records from the table file"})
            continue
        expect0 = np.array(recs[0][skip:skip + ncols])
        axis_inner = idx_names.index(innermost) if innermost in idx_names else len(idx_names) - 1
        first = tuple([0] * (table.ndim - 1))
        second = list(first); second[axis_inner] = 1; second = tuple(second)
        got0 = table[first][:ncols]
        if table.shape[-1] < ncols:
            out.append({"check": "table-reads", "severity": "FAIL", "name": name,
                        "detail": f"translation table has {table.shape[-1]} columns, the Fortran "
                                  f"reads {ncols} (`{prefix}1..{ncols})`)"})
            continue
        if not np.allclose(got0, expect0, rtol=1e-12, atol=0):
            # locate the shift for the message
            row = table[first]
            shift = next((s for s in range(1, 4) if row.shape[0] > ncols - 1 + s and
                          np.allclose(row[s:s + ncols - s], expect0[:ncols - s], rtol=1e-12, atol=0)),
                         None)
            hint = (f"columns are shifted by +{shift} slot(s): Fortran `{prefix}1)` must land at "
                    f"0-based slot 0" if shift else "values do not match the file's first record")
            out.append({"check": "table-reads", "severity": "FAIL", "name": name,
                        "detail": f"{hint} (file tokens {skip}:{skip + ncols} of record 1 ≠ "
                                  f"table{list(first)}[:{ncols}])"})
            continue
        expect1 = np.array(recs[1][skip:skip + ncols])
        if not np.allclose(table[second][:ncols], expect1, rtol=1e-12, atol=0):
            out.append({"check": "table-reads", "severity": "FAIL", "name": name,
                        "detail": f"record 2 of the file is not at table index {list(second)}: "
                                  f"the Fortran's innermost read loop is `{innermost}` (axis "
                                  f"{axis_inner} of {idx_names}) — loop nesting/axis order differs"})
            continue
        out.append({"check": "table-reads", "severity": "INFO", "name": name,
                    "detail": f"OK: {ncols} columns after {skip} leading tokens, base slot 0, "
                              f"innermost loop `{innermost}` → axis {axis_inner}; records 1–2 match"})
    return out


# --- 1a: direction-parameterised loop masks ---------------------------------
_ID_STRIDE_LOOP = re.compile(
    r"^\s*do\s+(\w+)\s*=\s*([A-Za-z_]\w*)\s*,\s*([A-Za-z_]\w*)\s*,\s*([-+]?)\s*([A-Za-z_]\w*)\s*$",
    re.I | re.M)


def _bound_stem(name: str) -> str:
    """'k_qxtop' → 'qxtop', 'ktop0' → 'top', 'k_qxbot - 1' → 'qxbot'."""
    n = re.sub(r"[^a-z]", "", name.lower())
    return re.sub(r"^k+", "", n)


def check_direction_masks(f_txt: str, p_txt: str) -> list[dict]:
    """1a (2026-08-25, heuristic WARN): a Fortran loop whose stride is an
    IDENTIFIER (`do k = A, B, -kdir`) becomes a whole-array mask
    `(x - y) * kdir >= 0` in the translation. For stride `-dir` the in-range
    test is (A - k)*dir >= 0 & (k - B)*dir >= 0; for `+dir` it is
    (k - A)*dir >= 0 & (B - k)*dir >= 0. Bounds are matched by name stem
    (ktop0 ↔ k_qxtop). Self-selecting: procedures without identifier-stride
    loops produce nothing. The exact check is the numerical symmetry test
    (bridge_test/test_direction_symmetry.py, 1b)."""
    loops = _ID_STRIDE_LOOP.findall(f_txt)
    if not loops:
        return []
    out = []
    terms = re.findall(r"\(\s*([A-Za-z_]\w*(?:\s*-\s*1)?)\s*-\s*([A-Za-z_]\w*(?:\s*-\s*1)?)\s*\)"
                       r"\s*\*\s*([A-Za-z_]\w*)\s*>=\s*0", p_txt)
    seen = set()
    for var, a, b, sign, dirv in loops:
        key = (a.lower(), b.lower(), sign, dirv.lower())
        if key in seen:
            continue
        seen.add(key)
        s = -1 if sign == "-" else 1
        rel = [t for t in terms if t[2].lower() == dirv.lower()]
        if not rel:
            out.append({"check": "direction-masks", "severity": "INFO",
                        "name": f"do {var}={a},{b},{sign}{dirv}",
                        "detail": "no `(x - y) * dir >= 0` mask found for this loop — "
                                  "cannot judge statically; rely on the symmetry test (1b)"})
            continue
        n_before = len(out)
        for x, y, _ in rel:
            sx, sy = _bound_stem(x), _bound_stem(y)
            for bound, is_start in ((a, True), (b, False)):
                sb = _bound_stem(bound)
                if not sb:
                    continue
                x_is_b = bool(sx) and (sb.endswith(sx) or sx.endswith(sb))
                y_is_b = bool(sy) and (sb.endswith(sy) or sy.endswith(sb))
                if x_is_b == y_is_b:
                    continue                    # neither/both look like this bound
                bound_first = x_is_b
                # correct: start bound first iff stride is -dir; end bound first iff +dir
                expect_first = (s == -1) if is_start else (s == 1)
                if bound_first != expect_first:
                    out.append({"check": "direction-masks", "severity": "WARN",
                                "name": f"{bound} in ({x} - {y})*{dirv}",
                                "detail": f"mask orientation looks inverted for `do {var} = {a}, "
                                          f"{b}, {sign}{dirv}`: expected "
                                          f"`({bound} - {var})` " if expect_first else
                                          f"mask orientation looks inverted for `do {var} = {a}, "
                                          f"{b}, {sign}{dirv}`: expected `({var} - {bound})` "
                                          f"for this bound (caught 08-25 in all sedimentation_*)"})
        if len(out) == n_before:
            out.append({"check": "direction-masks", "severity": "INFO",
                        "name": f"do {var}={a},{b},{sign}{dirv}",
                        "detail": f"{len(rel)} mask term(s) `(x - y) * {dirv} >= 0` found, "
                                  "orientation consistent with the loop stride"})
    return out


def check_conventions(p_src_raw: str) -> list[dict]:
    out = []
    if not LEVEL_CONVENTION_NAMES:
        return out
    names_alt = "|".join(re.escape(n) for n in LEVEL_CONVENTION_NAMES)
    claims = sorted(set(re.findall(
        rf"(?:{names_alt})\s*=\s*[-+]?\w+", p_src_raw)))
    if claims:
        out.append({
            "check": "conventions", "severity": "INFO", "name": "level-convention",
            "detail": "docstring/comment convention claims (cross-check against "
                      f"the caller's convention): {claims}",
        })
    return out


# ---------------------------------------------------------------------------
def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    waivers = {}
    if WAIVERS.exists():
        waivers = json.loads(WAIVERS.read_text(encoding="utf-8"))

    procs = sorted(p.stem for p in JAX_DIR.glob("*.py")
                   if p.stem != "__init__" and not p.stem.endswith(".validated")
                   and not re.search(r"_pass\d+$", p.stem))
    n_fail = n_warn = 0
    summary = []

    for proc in procs:
        f90 = find_f90(proc)
        if f90 is None:
            continue
        p_raw = (JAX_DIR / f"{proc}.py").read_text(encoding="utf-8", errors="replace")
        f_txt = strip_fortran(f90.read_text(encoding="utf-8", errors="replace"))
        p_txt = strip_python(p_raw)

        findings = []
        if "lut_indices" in ENABLED_CHECKS:
            findings += check_lut_indices(f_txt, p_txt)
        # generic checks — always run
        findings += (check_zero_forever(f_txt, p_txt)
                     + check_intent_out(f_txt, p_txt)
                     + check_constants(f_txt, p_txt)
                     + check_calls_invoked(proc, f_txt, p_txt)
                     + check_labelled_blocks(f_txt, p_raw))
        if PROGNOSTIC_VARS:
            findings += check_update_terms(f_txt, p_txt)
        if TABLE_READERS:
            findings += check_table_reads(proc, f_txt)
        findings += check_direction_masks(f_txt, p_txt)   # self-selecting (1a)
        if "level_conventions" in ENABLED_CHECKS:
            findings += check_conventions(p_raw)

        # apply waivers
        wv = waivers.get(proc, {})
        kept = []
        for f in findings:
            waived_names = set(map(str, wv.get(f["check"], [])))
            if f["name"] in waived_names:
                f["severity"] = "WAIVED"
            kept.append(f)

        fails = [f for f in kept if f["severity"] == "FAIL"]
        warns = [f for f in kept if f["severity"] == "WARN"]
        n_fail += len(fails)
        n_warn += len(warns)

        (OUT_DIR / f"{proc}.json").write_text(json.dumps({
            "proc": proc, "fortran": str(f90),
            "timestamp": datetime.now().isoformat(),
            "findings": kept,
        }, indent=2) + "\n", encoding="utf-8")

        if fails or warns:
            print(f"\n=== {proc} ===")
            for f in fails + warns:
                print(f"  [{f['severity']}] {f['check']} ({f['name']}): {f['detail']}")
        summary.append({"proc": proc, "fail": len(fails), "warn": len(warns),
                        "info": len([f for f in kept if f['severity'] == 'INFO'])})

    stamp = datetime.now().isoformat()
    (OUT_DIR / "_summary.json").write_text(json.dumps({
        "timestamp": stamp,
        "procs": summary, "total_fail": n_fail, "total_warn": n_warn,
    }, indent=2) + "\n", encoding="utf-8")

    # Durable, human-readable report next to the other Stage-2 reports
    # (0d, 2026-08-25): the JSONs are for the gate, this is for the record and
    # for Step 8's mandatory "Semantic audit" section.
    write_report(stamp, procs, summary, n_fail, n_warn)

    print(f"\nSemantic audit: {len(procs)} procs, "
          f"{n_fail} FAIL, {n_warn} WARN  (details in {OUT_DIR}/, "
          f"report {REPORT_MD})")
    return 2 if n_fail else 0


REPORT_DIR = PROJECT_ROOT / _CFG.reports_dir / "translation"
REPORT_MD = REPORT_DIR / "semantic_audit_report.md"

# Every check the script knows, with the config switch that enables it (None =
# always on). Listed in the report as ran / n/a so "no findings" is
# distinguishable from "never checked".
ALL_CHECKS = [
    ("lut-indices", "lut_indices", "FAIL", "translation uses LUT columns the Fortran never uses"),
    ("lut-indices-unported", "lut_indices", "WARN", "Fortran LUT columns the translation never fetches"),
    ("calls-invoked", None, "FAIL", "a procedure the Fortran calls is never invoked in the translation body (X( / X_core( / X_value( )"),
    ("labelled-blocks", None, "WARN", "a Fortran labelled block (name: if/do/…) is not mentioned anywhere in the translation"),
    ("update-terms", "prognostic_vars", "FAIL", "a term of the Fortran `x = x ± (…)` prognostic update is absent from the translation's update of x"),
    ("update-terms-extra", "prognostic_vars", "WARN", "the translation's update of x has terms the Fortran's does not"),
    ("direction-masks", None, "WARN", "heuristic: `(x - y) * dir >= 0` mask orientation vs the Fortran `do k = A, B, ±dir` loop (only procedures with identifier-stride loops; exact check = bridge_test/test_direction_symmetry.py)"),
    ("table-reads", "table_readers", "FAIL", "lookup-table reader executed on the real file: column base slot, column count, leading-token skip and loop nesting must match the Fortran read statement"),
    ("zero-forever", None, "WARN", "Fortran computes it, translation only ever assigns zero (chained assignments split)"),
    ("intent-out", None, "WARN", "intent(out) argument never freshly assigned"),
    ("missing-consts", None, "WARN", "Fortran numeric literals absent from the translation"),
    ("invented-consts", None, "INFO", "translation literals absent from the Fortran"),
    ("conventions", "level_conventions", "INFO", "level/index convention claims for manual cross-check"),
]


def write_report(stamp: str, procs: list[str], summary: list[dict],
                 n_fail: int, n_warn: int) -> None:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    llm = _CFG.section("translator").get("llm_label", "?")
    waivers_note = f"`{WAIVERS.relative_to(PROJECT_ROOT)}`" if WAIVERS.exists() else "none"
    rows, n_waived = [], 0
    per_proc = []
    for s in summary:
        d = json.loads((OUT_DIR / f"{s['proc']}.json").read_text(encoding="utf-8"))
        fs = d["findings"]
        w = sum(1 for f in fs if f["severity"] == "WAIVED")
        n_waived += w
        per_proc.append((s["proc"], s["fail"], s["warn"], w, s["info"]))
        for f in fs:
            if f["severity"] in ("FAIL", "WARN", "WAIVED"):
                rows.append((s["proc"], f["check"], f["severity"], f["name"],
                             f["detail"].replace("|", "\\|")))
    verdict = "FAIL" if n_fail else "PASS"
    lines = [
        "# Semantic audit report (TRANSLATE_WORKFLOW Step 3.5a)", "",
        f"| | |", "|---|---|",
        f"| run | {stamp} |", f"| translator | {llm} |",
        f"| procedures audited | {len(procs)} |",
        f"| verdict | **{verdict}** — {n_fail} FAIL, {n_warn} WARN, {n_waived} waived |",
        f"| waivers file | {waivers_note} |",
        f"| gate | `workflow_translator/audit_gate.py` reads `{(OUT_DIR / '_summary.json').relative_to(PROJECT_ROOT)}`; "
        f"runtime validation (Step 4) requires 0 FAIL and this report newer than every `out/jax/<proc>.py` |",
        "", "## Checks", "",
        "| check | severity | status in this project | meaning |", "|---|---|---|---|",
    ]
    for name, switch, sev, meaning in ALL_CHECKS:
        if switch is None or switch in ENABLED_CHECKS:
            status = "ran"
        elif switch == "prognostic_vars":
            status = ("ran" if PROGNOSTIC_VARS else
                      "n/a — `[semantic_audit].prognostic_vars` not set")
        elif switch == "table_readers":
            status = ("ran" if TABLE_READERS else
                      "n/a — `[semantic_audit].table_readers` not set (no lookup tables)")
        else:
            status = f"n/a — `{switch}` not in `[semantic_audit].enabled_checks`"
        lines.append(f"| {name} | {sev} | {status} | {meaning} |")
    lines += ["", "## Per procedure", "",
              "| procedure | FAIL | WARN | waived | INFO |", "|---|---|---|---|---|"]
    for p, f, w, wv, i in per_proc:
        lines.append(f"| {p} | {f} | {w} | {wv} | {i} |")
    lines += ["", "## Findings (FAIL / WARN / waived)", ""]
    if rows:
        lines += ["| procedure | check | severity | name | detail |", "|---|---|---|---|---|"]
        order = {"FAIL": 0, "WARN": 1, "WAIVED": 2}
        for p, c, sev, nm, det in sorted(rows, key=lambda r: (order[r[2]], r[0], r[1], r[3])):
            lines.append(f"| {p} | {c} | {sev} | `{nm}` | {det} |")
    else:
        lines.append("_none_")
    lines += ["", f"Machine-readable findings: `{OUT_DIR.relative_to(PROJECT_ROOT)}/<proc>.json`, "
                  f"summary `_summary.json`.", ""]
    REPORT_MD.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    sys.exit(main())
